/**
 * ApiLibrary
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateLoanDto { 
    bookId?: number;
    userId?: number;
    date?: string;
    plannedReturningDate?: string;
}

