/**
 * ApiLibrary
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLoanDto { 
    id?: number;
    bookId?: number;
    userId?: number;
    bookAuthorId?: number;
    date?: string;
    plannedReturningDate?: string;
    effectiveReturningDate?: string | null;
    bookTitle?: string | null;
    userFirstName?: string | null;
    userLastName?: string | null;
    userEmail?: string | null;
    userBirthDate?: string | null;
    bookReleaseYear?: number | null;
    bookISBN?: string;
    bookAuthorName?: string | null;
    bookAuthorFirstname?: string | null;
}

