/**
 * ApiLibrary
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetBookDto { 
    id?: number;
    title?: string;
    authorId?: number;
    releaseYear?: number | null;
    isbn?: string;
    authorFullName?: string | null;
}

