/**
 * ApiLibrary
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateUserDto { 
    firstName?: string;
    lastName?: string;
    email?: string;
    birthDate?: string | null;
}

